### ISSUE TITLE
Useless classes and trouble in file handling.

### ISSUE THREAD

**Issue by OmerJauhar** [Skaps664/RateIt-QT-Application-with-OOP-C-#2]
The classes such as hostel , university  are useless because they are not being used in the proper way . Their instances are created and data members are allotted  its  values but no certain function of the class is called .  Even in the dialog.cpp files of the classes data is fetched from the user through ui->line->text() commands but they are simply allocated to the data members of the classes , whereas for file handling instead of calling a member function to do the task , again data is fetched from the ui and stored in variables which intend to perform the file handling task . 
Either create member functions to perform file handling or do not use classes at all . 
Similarly multiple errors in the working of the file handling . 
![image](https://user-images.githubusercontent.com/95120715/175312859-40d3926f-4dff-4ec6-936f-a264525a4a3b.png)

**Comment by Skaps664** [comment]
Yes. That's what I have mentioned in the Readme file. It's was a very basic try and will be best for anyone to use this PROJECT, had to do some work on their own too.
